enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0082
    level: discard
  - code: YN0002
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
