services:
  slack-viewer:
    build: .
    container_name: slack-viewer-app
    ports:
      - '5173:5173'
    volumes:
      - ${SLACK_HISTORY_DATA_PATH:-./data}:/data:ro
      - app_db_data:/db:rw
    environment:
      - NODE_ENV=production
      - SLACK_HISTORY_DATA_PATH=/data
      - SLACK_SOLR_HOST=solr
      - SLACK_SOLR_PORT=8983
      - SLACK_SOLR_CORE=${SLACK_SOLR_CORE:-slack_messages}
      - SLACK_DB_FILENAME=/db/processed_messages.db
    restart: unless-stopped
    depends_on:
      solr:
        condition: service_healthy

  solr:
    image: solr:9
    container_name: slack-viewer-solr
    ports:
      - '8983:8983'
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - ${SLACK_SOLR_CORE:-slack_messages}
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:8983/solr/${SLACK_SOLR_CORE:-slack_messages}/admin/ping',
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  solr_data:
  app_db_data:
